add getAnimationInfo and getAnimationClip APIs & update some dependencies
BloomBeat/SignBloom3D pull request #27
Opened 2024-10-09 12:37 UTC by KantawitCH

GET  getAnimationInfo

2024-10-09 12:42 UTC, Chatchaponz requested changes

2024-10-09 12:42 UTC, Chatchaponz commented on server/controllers/animationController.js
> +        const animationInfo = await axios.get('https://recorder.justsigns.co/api/animation/info', {
Recorder endpoints should be in `.env` file

2024-10-09 12:42 UTC, Chatchaponz commented on server/controllers/animationController.js
> +        const animationClip = await axios.get(`https://recorder.justsigns.co/api/animation/clip/${id}`);
Recorder endpoints should be in `.env` file

2024-10-09 14:41 UTC, Chatchaponz approved these changes

2024-10-10 04:19 UTC, wutpppppppppppppppppp approved these changes

2024-10-10 04:19 UTC, merged